app = "c3-template-app"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  DATABASE_URL = "sqlite:////app/data/data.db"

[[mounts]]
  source = "data"
  destination = "/app/data"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]